### PR TITLE
Multi must test

### PR DESCRIPTION
**Pull request by teone**
Update `WalkAndValidateMust` to iterate over every node in the tree

### CODE REVIEW

**Comment by teone** [comment]
Still having some issues in writing a unit test, seems like I can't write a `must` statement that will select the correct node.

**Comment by SeanCondon** [comment]
> Still having some issues in writing a unit test, seems like I can't write a `must` statement that will select the correct node.

@teone - the thing here is that you are navigating through the YANG entiies to find the "must" statements, but you're not moving the pointer to "curr" in the `YangNodeNavigator` - this is what gives you the context for the `Evaluate`. I think it's better to traverse the `YangNodeNavigator` using the down and across method, but just fix some deficiency it had in getting to all points it had on it

**Comment by SeanCondon** [comment]
@teone can we close this - the problem has been fixed here #218

**Comment by ray-milkey** [comment]
This was implemented in another PR.

**Pull request closed without merging**
